import dayjs from "dayjs";
import { WorkExperience } from "./types";

import utopiaLogo from "@/app/assets/utopia-advertising-egypt.png";
import divineTouchLogo from "@/app/assets/divine-touch.png";
import shatableeLogo from "@/app/assets/shatablee.png";
import luciqLogo from "@/app/assets/luciq.png";
import genericStartupLogo from "@/app/assets/generic-startup.png";
import coachAcademyLogo from "@/app/assets/coach-academy.png";

export const experience: WorkExperience[] = [
  {
    company: {
      name: "Luciq (formerly Instabug)",
      organisationUrl: "https://www.luciq.ai",
      location: "San Francisco, California, United States · Remote",
      icon: luciqLogo,
    },
    roles: [
      {
        title: "Backend Software Engineer",
        employmentType: "Part-time",
        description:
          "Backend-focused software engineer working on internal platforms and infrastructure-heavy systems.",
        descriptionPoints: [
          "Led the development of a Go/React internal SaaS replacement, saving $40k+ annually while exceeding the old system’s functionality and performance.",
          "Migrated organization-wide authentication to GitHub Apps, improving security posture and reducing operational overhead.",
          "Redesigned and scaled the internal hiring/testing platform used across engineering teams.",
          "Mentored an intern end-to-end, enabling them to ship high-impact production features independently.",
        ],
        startDate: dayjs("2024-09-01"),
      },
      {
        title: "Backend Software Engineer Intern",
        employmentType: "Internship",
        description:
          "Worked on backend-heavy internal tooling using Go and React, deployed on AWS.",
        descriptionPoints: [
          "Built and shipped phase one of an internal platform that later evolved into a $40k+/year cost-saving system.",
          "Developed a Go-based visualization tool to graph internal package dependencies while excluding external libraries.",
        ],
        startDate: dayjs("2024-07-01"),
        endDate: dayjs("2024-09-30"),
      },
    ],
  },
  {
    company: {
      name: "Hobbify",
      organisationUrl: "https://en.wikipedia.org/wiki/Startup_company",
      location: "Cairo, Egypt · Remote",
      icon: genericStartupLogo,
    },
    roles: [
      {
        title: "Full Stack Software Engineer",
        employmentType: "Part-time",
        description:
          "Full-stack engineer responsible for backend APIs and scalable cross-platform applications.",
        descriptionPoints: [
          "Architected Flask REST APIs with Marshmallow validation and autogenerated Swagger documentation.",
          "Designed and implemented CI/CD pipelines and deployed backend services on Render.",
          "Built Flutter applications using feature-based architecture and GoRouter for long-term scalability.",
          "Implemented state management using Riverpod and MobX.",
          "Handled localization (l10n/i18n) for multilingual mobile applications.",
          "Integrated REST APIs using Chopper with strongly typed Freezed models.",
        ],
        startDate: dayjs("2023-10-01"),
        endDate: dayjs("2024-07-31"),
      },
    ],
  },
  {
    company: {
      name: "Divine Touch Productions",
      organisationUrl: "https://www.facebook.com/DivineTouchProductions/",
      location: "Cairo, Egypt",
      icon: divineTouchLogo,
    },
    roles: [
      {
        title: "Technical Project Manager",
        employmentType: "Part-time",
        description:
          "Owned delivery planning and technical execution for cross-platform mobile teams.",
        descriptionPoints: [
          "Led Agile sprints for Cross functional teams, improving delivery predictability and velocity.",
          "Standardized reporting metrics and sprint tracking to improve stakeholder visibility.",
          "Acted as the technical bridge between product, design, and engineering teams.",
        ],
        startDate: dayjs("2022-09-01"),
        endDate: dayjs("2023-09-30"),
      },
      {
        title: "Software Engineer",
        employmentType: "Full-time",
        description:
          "Cross-platform software engineer and UI/UX designer across mobile and desktop products.",
        descriptionPoints: [
          "Built production mobile applications using React Native and Redux Toolkit.",
          "Developed Flutter desktop applications using Riverpod for state management.",
          "Designed complete UI/UX systems and design libraries using Adobe XD.",
          "Integrated RESTful APIs and managed app-side networking layers.",
        ],
        startDate: dayjs("2021-12-01"),
        endDate: dayjs("2022-09-30"),
      },
    ],
  },
  {
    company: {
      name: "Shatablee",
      organisationUrl: "https://www.facebook.com/shatablee/",
      location: "Cairo, Egypt",
      icon: shatableeLogo,
    },
    roles: [
      {
        title: "Frontend Software Engineer",
        employmentType: "Full-time",
        description:
          "Owned the development and release lifecycle of a production Flutter application.",
        descriptionPoints: [
          "Engineered a Flutter application using MVC architecture.",
          "Implemented state management, dependency injection, and navigation using GetX.",
          "Managed RESTful API integration using Chopper.",
          "Handled full App Store and Play Store release cycles.",
          "Implemented localization (i18n/l10n) tailored for the MENA market.",
        ],
        startDate: dayjs("2022-09-01"),
        endDate: dayjs("2023-07-31"),
      },
    ],
  },
  {
    company: {
      name: "Coach Academy ME",
      organisationUrl: "https://coach-academy.net",
      location: "Cairo, Egypt",
      icon: coachAcademyLogo,
    },
    roles: [
      {
        title: "Competitive Programming Tutor",
        employmentType: "Part-time",
        description:
          "Instructor specializing in algorithms, data structures, and competitive programming.",
        descriptionPoints: [
          "Delivered 400+ hours of C++ and algorithm lectures to 700+ students.",
          "Authored 120+ original problem sets covering core competitive programming topics.",
          "Designed full curricula ranging from basic programming to advanced algorithms.",
          "Provided live mentorship, debugging sessions, and performance feedback.",
        ],
        startDate: dayjs("2021-09-01"),
        endDate: dayjs("2023-01-31"),
      },
    ],
  },
  {
    company: {
      name: "Utopia Advertising Egypt",
      organisationUrl: "https://www.facebook.com/UtopiaAdEgypt/",
      location: "Cairo, Egypt",
      icon: utopiaLogo,
    },
    roles: [
      {
        title: "Graphic Design Intern",
        employmentType: "Internship",
        description:
          "Graphic designer supporting large-scale marketing and branding campaigns.",
        descriptionPoints: [
          "Designed marketing assets for campaigns deployed across 600+ pharmacies nationwide.",
          "Worked on creative materials for major brands, including Abbott (Brufen campaign).",
          "Produced logos, branding kits, and social media assets for multiple clients.",
        ],
        startDate: dayjs("2019-07-01"),
        endDate: dayjs("2019-09-30"),
      },
    ],
  },
];
