import dayjs from "dayjs";
import { WorkExperience } from "./types";

import utopiaLogo from "@/app/assets/utopia-adevertising-egypt.png";
import divineTouchLogo from "@/app/assets/divine-touch.jpeg";
import shatableeLogo from "@/app/assets/shatablee.jpeg";
// import luciqLogo from "@/app/assets/luciq.png";
// import hobbifyLogo from "@/app/assets/hobbify.png";
// import coachAcademyLogo from "@/app/assets/coach-academy.png";
// import dafLogo from "@/app/assets/daf.png";

export const experience: WorkExperience[] = [
  {
    company: {
      name: "Luciq",
      organisationUrl: "https://www.luciq.ai",
      location: "San Francisco, California, United States · Hybrid",
      icon: divineTouchLogo,
    },
    roles: [
      {
        title: "Back End Developer",
        employmentType: "Part-time",
        description:
          "Developing backend services using Go and Next.js. Building performant REST APIs and integrating backend logic with front-end applications.",
        descriptionPoints: [
          "Designing and maintaining scalable REST APIs with Go.",
          "Implementing integrations between backend services and Next.js apps.",
          "Optimizing database queries for performance and reliability.",
        ],
        startDate: dayjs("2024-09-01"),
      },
      {
        title: "Back End Developer",
        employmentType: "Internship",
        description:
          "Contributed to backend development using Go and Next.js. Focused on building scalable REST APIs and improving server performance.",
        descriptionPoints: [
          "Implemented CRUD endpoints for multiple microservices.",
          "Improved API latency by optimizing middleware and caching.",
          "Collaborated with frontend developers to debug and enhance API reliability.",
        ],
        startDate: dayjs("2024-07-01"),
        endDate: dayjs("2024-09-30"),
      },
    ],
  },
  {
    company: {
      name: "Hobbify",
      organisationUrl: "https://hobbify.example.com",
      location: "Cairo, Egypt · Remote",
      icon: divineTouchLogo,
    },
    roles: [
      {
        title: "Full Stack Engineer",
        employmentType: "Part-time",
        description:
          "Developed Flutter apps and Flask-based backend services, focusing on clean architecture and CI/CD deployment.",
        descriptionPoints: [
          "Built Flutter apps using feature-based architecture and GoRouter.",
          "Used Riverpod and MobX for state management.",
          "Localized mobile apps with l10n.",
          "Integrated RESTful APIs using Chopper and Freezed models.",
          "Developed Flask REST APIs with autogenerated Swagger UI using Flask-RESTX.",
          "Validated data using Flask-Marshmallow.",
          "Deployed backend to Render with CI/CD automation.",
        ],
        startDate: dayjs("2023-10-01"),
        endDate: dayjs("2024-07-31"),
      },
    ],
  },
  {
    company: {
      name: "Divine Touch Productions",
      organisationUrl: "https://divinetouch.example.com",
      location: "Cairo, Egypt",
      icon: divineTouchLogo,
    },
    roles: [
      {
        title: "Project Manager",
        employmentType: "Part-time",
        description:
          "Planned and managed agile sprints for a React Native app while coordinating a small dev team.",
        descriptionPoints: [
          "Organized weekly sprints using Agile methodologies.",
          "Monitored team progress and improved productivity metrics.",
          "Prepared detailed weekly progress and performance reports.",
        ],
        startDate: dayjs("2022-09-01"),
        endDate: dayjs("2023-09-30"),
      },
      {
        title: "Software Engineer",
        employmentType: "Full-time",
        description:
          "Worked as a cross-platform developer and UI/UX designer on multiple projects.",
        descriptionPoints: [
          "Built mobile apps with React Native and Redux Toolkit.",
          "Developed desktop apps using Flutter and Riverpod.",
          "Managed RESTful API requests with DIO.",
          "Designed full UI/UX systems using Adobe XD.",
        ],
        startDate: dayjs("2021-12-01"),
        endDate: dayjs("2022-09-30"),
      },
    ],
  },
  {
    company: {
      name: "Shatablee",
      organisationUrl: "https://shatablee.example.com",
      location: "Cairo, Egypt",
      icon: shatableeLogo,
    },
    roles: [
      {
        title: "Software Engineer",
        employmentType: "Full-time",
        description:
          "Developed cross-platform applications using Flutter with robust architecture and localization.",
        descriptionPoints: [
          "Used Flutter with MVC architecture.",
          "Implemented state management, navigation, and DI with GetX.",
          "Localized apps with l10n and managed REST APIs using Chopper.",
        ],
        startDate: dayjs("2022-09-01"),
        endDate: dayjs("2023-07-31"),
      },
    ],
  },
  {
    company: {
      name: "Coach Academy ME",
      organisationUrl: "https://coachacademy.example.com",
      location: "Cairo, Egypt",
      icon: divineTouchLogo,
    },
    roles: [
      {
        title: "Competitive Programming Tutor",
        employmentType: "Part-time",
        description:
          "Taught C++ programming and problem-solving fundamentals to hundreds of students.",
        descriptionPoints: [
          "Created complete course structure, slides, and problem sets.",
          "Covered topics from loops and arrays to bitmasking and number theory.",
          "Hosted live support sessions and designed practice sheets per topic.",
        ],
        startDate: dayjs("2021-09-01"),
        endDate: dayjs("2023-01-31"),
      },
    ],
  },
  {
    company: {
      name: "Utopia Advertising Egypt",
      organisationUrl: "https://www.facebook.com/UtopiaAdEgypt/",
      location: "Cairo, Egypt",
      icon: utopiaLogo,
    },
    roles: [
      {
        title: "Graphic Design Intern",
        employmentType: "Internship",
        description:
          "Created visual assets and branding materials for nationwide marketing campaigns.",
        descriptionPoints: [
          "Designed banners and ads for 600+ pharmacies in Egypt.",
          "Worked on the Abbott Brufen campaign creative materials.",
          "Developed logos and personal branding kits for clients.",
        ],
        startDate: dayjs("2019-07-01"),
        endDate: dayjs("2019-09-30"),
      },
    ],
  },
];
